---

- name: Insert/Update configfile
  blockinfile:
    path: /boot/config.txt
    block: |
      dtoverlay=rpi-poe-plus 
      dtparam=poe_fan_temp0=45000,poe_fan_temp0_hyst=2000 
      dtparam=poe_fan_temp1=55000,poe_fan_temp1_hyst=5000 
      dtparam=poe_fan_temp2=60000,poe_fan_temp2_hyst=5000 
      dtparam=poe_fan_temp3=65000,poe_fan_temp3_hyst=7000