---
# handlers file for setup
- name: update hostname
  command: "hostname {{ multi_hostname }}"

- name: delete dhcp leases
  file:
    path: /var/lib/dhcp/dhclient.leases
    state: absent
  with_items:
    - /var/lib/dhcp/dhclient.leases
    - /var/lib/dhcpcd5/dhcpcd-eth0.lease