---

- hosts: multi
  gather_facts: yes
  become: yes
  roles:
    - role: k3s-setup/prereq
    - role: k3s-setup/download
    - role: k3s-setup/raspberrypi

- hosts: master
  become: yes
  roles:
    - role: k3s-setup/k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s-setup/k3s/node
