---
- hosts: multi
  # become = run as sudo
  become: yes

  pre_tasks:
    - name: Test Ping
      ansible.builtin.ping:

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
         update_cache: true
         cache_valid_time: 3600
    - name: Update all packages to the latest version
      apt:
        upgrade: dist